# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
Vagrant.configure(2) do |config|
    config.hostmanager.enabled = true
	  config.hostmanager.ignore_private_ip = false
	  config.hostmanager.include_offline = true

    config.vm.define "puppet" do |puppet|
	    # Puppetmaster on CentOS 7
		  config.vm.provider "virtualbox" do |v|
		      v.memory = 2048
		  end
      puppet.vm.synced_folder ".", "/vagrant"
      puppet.vm.synced_folder "../code", "/puppet_code"
      puppet.vm.synced_folder "../puppetserver", "/puppet_puppetserver"
	  	puppet.vm.box = "boxcutter/centos72"
		  puppet.vm.hostname = "puppet.johantanadi.com"
		  puppet.vm.network :private_network, ip: "10.0.0.10"
	  	puppet.hostmanager.aliases = %w(puppet)
	  	puppet.vm.provision "shell", inline: <<-SHELL
		      sudo yum update -y
			    sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
			    sudo yum install puppetserver -y
          sudo rm -rf /etc/puppetlabs/code
          sudo ln -s /puppet_code /etc/puppetlabs/code
          sudo rm -rd /etc/puppetlabs/puppetserver
          sudo ln -s /puppet_puppetserver /etc/puppetlabs/puppetserver
		    	sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
          echo "*.johantanadi.com" | sudo tee /etc/puppetlabs/puppet/autosign.conf
          sudo service puppetserver start
	  	SHELL
    	end

	  config.vm.define "agent1" do |agent1|
	    # Puppet agent on CentOS 7
		  agent1.vm.box = "boxcutter/centos72"
	  	agent1.vm.hostname = "agent1.johantanadi.com"
	  	agent1.vm.network :private_network, ip: "10.0.0.11"
	  	agent1.hostmanager.aliases = %w(agent1)
      agent1.vm.provision "shell", inline: <<-SHELL
          sudo yum update -y
          sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
          sudo yum install puppet-agent -y
          sudo service puppet start
          SHELL
     	end

	  config.vm.define "agent2" do |agent2|
	    # Puppet agent on Debian
	  	agent2.vm.box = "ARTACK/debian-jessie"
	  	agent2.vm.hostname = "agent2.johantanadi.com"
	  	agent2.vm.network :private_network, ip: "10.0.0.12"
	  	agent2.hostmanager.aliases = %w(agent2)
      agent2.vm.provision "shell", inline: <<-SHELL
           wget https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb
           sudo dpkg -i puppetlabs-release-pc1-jessie.deb
           sudo apt-get update
           sudo apt-get install puppet-agent -y
           sudo /opt/puppetlabs/bin/puppet agent --enable
           sudo service puppet start
      SHELL
	  end

    config.vm.define "agent3" do |agent3|
	    # Puppet agent on Windows 2012
	  	agent3.vm.box = "devopsguys/Windows2012R2Eval"
	  	agent3.vm.hostname = "agent3.johantanadi.com"
	  	agent3.vm.network :private_network, ip: "10.0.0.13"
	  	agent3.hostmanager.aliases = %w(agent3)
      agent3.vm.provision "shell", :path => "windows.ps1"
	  end
end
